### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Henriiig** [magemonkeystudio/genesis#99] opened 2024-10-20 13:31 UTC
https://pastebin.com/mifS4rSQ

Im on 1.20.6 papermc

Also: Would it be possible to add the TrickyShops addon and how about shops for citizens like the integration?

**Comment by Travja** [comment] 2024-10-20 17:20
I'll have to put in a fix for this. Just FYI, the issue isn't present in 1.21.1

**Closed** 2024-10-25 05:34 UTC
